### ISSUE TITLE
Prisonmainblock causing crash on foot at ranch.

### ISSUE THREAD

**Issue by Duguayster** [qbcore-framework/prison_map#1]
AFter testing for 5 hours, I've been able to identify this resource and Prisonmainblock is the culprit for the follow crash I've captured on video and placed on youtube for you.

Note, the crash occurs only when on foot, not while in a vehicle.

https://www.youtube.com/watch?v=_XWAOrewlcg

Thanks

**Comment by SirOMGitsYOU** [comment]
Has there been any update with this potentially having a fix in sight?
